neurovault/apps/statmaps/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView
from django.views.generic.base import RedirectView

from neurovault import settings
from neurovault.apps.statmaps.models import KeyValueTag
from neurovault.apps.statmaps.views import (
    ImagesInCollectionJson,
    PublicCollections,
    PublicCollectionsJson,
    MyCollections,
    MyCollectionsJson,
    AtlasesAndParcellationsJson,
    ImagesByTaskJson,
    GroupImagesInCollectionJson,
    SingleSubjectImagesInCollectionJson,
    OtherImagesInCollectionJson,
    AllDOIPublicGroupImages,
    MyMetaanalysesJson,
    toggle_active_metaanalysis,
)
from .views import (
    edit_collection,
    view_image,
    delete_image,
    edit_image,
    view_collection,
    delete_collection,
    download_collection,
    upload_folder,
    add_image_for_neurosynth,
    serve_image,
    serve_pycortex,
    view_collection_with_pycortex,
    papaya_js_embed,
    view_images_by_tag,
    add_image_for_neuropower,
    view_image_with_pycortex,
    stats_view,
    serve_nidm,
    serve_nidm_image,
    view_nidm_results,
    find_similar,
    find_similar_json,
    compare_images,
    edit_metadata,
    export_images_filenames,
    delete_nidm_results,
    view_task,
    search,
    serve_surface_archive,
    edit_metaanalysis,
    view_metaanalysis,
    activate_metaanalysis,
    finalize_metaanalysis,
    gene_expression,
    gene_expression_json,
)

app_name = "statmaps"

urlpatterns = [
    re_path(
        r"^metaanalysis_selection/$",
        TemplateView.as_view(template_name="statmaps/metaanalysis_selection.html"),
        name="metaanalysis_selection",
    ),
    re_path(
        r"^my_metaanalyses/$",
        login_required(
            TemplateView.as_view(template_name="statmaps/my_metaanalyses.html")
        ),
        name="my_metaanalyses",
    ),
    re_path(r"^my_metaanalyses/new$", edit_metaanalysis, name="new_metaanalysis"),
    re_path(
        r"^metaanalyses/(?P<metaanalysis_id>\d+)/edit$",
        edit_metaanalysis,
        name="edit_metaanalysis",
    ),
    re_path(
        r"^metaanalyses/(?P<metaanalysis_id>\d+)/activate$",
        activate_metaanalysis,
        name="activate_metaanalysis",
    ),
    re_path(
        r"^metaanalyses/(?P<metaanalysis_id>\d+)/finalize$",
        finalize_metaanalysis,
        name="finalize_metaanalysis",
    ),
    re_path(
        r"^metaanalyses/(?P<metaanalysis_id>\d+)$",
        view_metaanalysis,
        name="view_metaanalysis",
    ),
    re_path(
        r"^metaanalyses/(?P<metaanalysis_id>\d+)/images_json",
        AllDOIPublicGroupImages.as_view(),
        name="metaanalysis_images_json",
    ),
    re_path(
        r"^my_metaanalyses/json$",
        login_required(MyMetaanalysesJson.as_view()),
        name="my_metaanalyses_json",
    ),
    re_path(
        r"^metaanalysis_selection/json$",
        AllDOIPublicGroupImages.as_view(),
        name="metaanalysis_selection_json",
    ),
    re_path(
        r"^my_collections/$",
        MyCollections.as_view(),
        name="my_collections",
    ),
    re_path(
        r"^my_collections/json$",
        login_required(MyCollectionsJson.as_view()),
        name="my_collections_json",
    ),
    re_path(
        r"^collections/$",
        PublicCollections.as_view(),
        name="collections_list",
    ),
    re_path(
        r"^collections/json$",
        PublicCollectionsJson.as_view(),
        name="collections_list_json",
    ),
    re_path(r"^collections/stats$", stats_view, name="collections_stats"),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/$",
        view_collection,
        name="collection_details",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/json$",
        ImagesInCollectionJson.as_view(),
        name="collection_images_json",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/gjson$",
        GroupImagesInCollectionJson.as_view(),
        name="collection_gimages_json",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/sjson$",
        SingleSubjectImagesInCollectionJson.as_view(),
        name="collection_simages_json",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/ojson$",
        OtherImagesInCollectionJson.as_view(),
        name="collection_oimages_json",
    ),
    re_path(r"^collections/new$", edit_collection, name="new_collection"),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/edit$",
        edit_collection,
        name="edit_collection",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/delete$",
        delete_collection,
        name="delete_collection",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/download$",
        download_collection,
        name="download_collection",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/upload_folder$",
        upload_folder,
        name="upload_folder",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/images/(?P<pk>\d+)/$",
        view_image,
        name="private_image_details",
    ),
    re_path(
        r"^collections/(?P<cid>\d+|[\w{}.-]{8})/pycortex$",
        view_collection_with_pycortex,
        name="view_collection_pycortex",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/export/imagesfilenames$",
        export_images_filenames,
        name="export_images_filenames",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/editmetadata$",
        edit_metadata,
        name="edit_metadata",
    ),
    re_path(
        r"^atlases/$",
        TemplateView.as_view(template_name="statmaps/atlases.html"),
        name="atlases_and_parcellations",
    ),
    re_path(
        r"^atlases/json$",
        AtlasesAndParcellationsJson.as_view(),
        name="atlases_and_parcellations_json",
    ),
    re_path(
        r"^images/tags/$",
        ListView.as_view(
            queryset=KeyValueTag.objects.all(),
            context_object_name="tags",
            template_name="statmaps/tags_index.html",
        ),
        name="tags_list",
    ),
    re_path(
        r"^images/tags/(?P<tag>[A-Za-z0-9@\.\+\-\_\s]+)/$",
        view_images_by_tag,
        name="images_by_tag",
    ),
    re_path(r"^images/(?P<pk>\d+)/$", view_image, name="image_details"),
    re_path(
        r"^images/(?P<pk>\d+)/toggle_active_meta$",
        toggle_active_metaanalysis,
        name="toggle_active_metaanalysis",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/images/(?P<pk>\d+)/toggle_active_meta$",
        toggle_active_metaanalysis,
        name="private_toggle_active_metaanalysis",
    ),
    re_path(
        r"^images/(?P<pk>\d+)/pycortex$",
        view_image_with_pycortex,
        name="pycortex_view_image",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/images/(?P<pk>\d+)/pycortex$",
        view_image_with_pycortex,
        name="private_pycortex_view_image",
    ),
    re_path(r"^images/(?P<pk>\d+)/edit$", edit_image, name="edit_image"),
    re_path(r"^images/(?P<pk>\d+)/delete$", delete_image, name="delete_image"),
    re_path(
        r"^images/add_for_neurosynth$",
        add_image_for_neurosynth,
        name="add_for_neurosynth",
    ),
    re_path(
        r"^images/add_for_neuropower$",
        add_image_for_neuropower,
        name="add_for_neuropower",
    ),
    re_path(r"^images/(?P<pk>\d+)/js/embed$", papaya_js_embed, name="papaya_js_embed"),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/(?P<nidm_name>[A-Za-z0-9\.\+\-\_\s\[\]\(\)]+\.nidm\_?[0-9]*)/?$",
        view_nidm_results,
        name="view_nidm_results",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/(?P<nidm_name>[A-Za-z0-9\.\+\-\_\s\[\]\(\)]+\.nidm\_?[0-9]*)/delete$",
        delete_nidm_results,
        name="delete_nidm_results",
    ),
    re_path(
        r"^images/(?P<pk>\d+)/papaya/embedview$",
        papaya_js_embed,
        {"iframe": True},
        name="papaya_iframe_embed",
    ),
    re_path(
        r"^media/images/(?P<collection_cid>\d+|[\w{}.-]{8})/(?P<img_name>[0-9a-zA-Z\^\&\'\@\{\}\[\]\,\$\=\!\-\#\(\)\.\%\+\~\_ ]+)$",
        serve_image,
        name="serve_image",
    ),
    re_path(
        r"^images/(?P<pk>\d+)/download_surfaces$",
        serve_surface_archive,
        name="serve_surface_archive",
    ),
    re_path(
        r"^collections/(?P<collection_cid>\d+|[\w{}.-]{8})/images/(?P<pk>\d+)/download_surfaces$",
        serve_surface_archive,
        name="serve_surface_archive",
    ),
    re_path(
        r"^media/images/(?P<collection_cid>\d+|[\w{}.-]{8})/(?P<nidmdir>[0-9a-zA-Z\^\&\'\@\{\}\[\]\,\$\=\!\-\#\(\)\.\%\+\~\_ ]+\.nidm\_?[0-9]*)(?P<sep>\.|/)(?P<path>.*)$",
        serve_nidm_image,
        name="serve_nidm_images",
    ),
    # redirect dynamically loaded pycortex scripts
    re_path(
        r"^media/images/(\d+|[\w{}.-]{8})/(.*_pycortex|pycortex_all)/resources/(?P<path>.*).js$",
        RedirectView.as_view(
            url="{0}pycortex-resources/%(path)s.js".format(settings.STATIC_URL)
        ),
        name="redirect_pycortex_js",
    ),
    # redirect cached ctm assets
    re_path(
        r"^media/images/(\d+|[\w{}.-]{8})/(.*_pycortex|pycortex_all)/(?P<ctmfile>fsaverage.*).(?P<ext>json|svg|ctm)$",
        RedirectView.as_view(
            url="{0}pycortex-ctmcache/%(ctmfile)s.%(ext)s".format(settings.STATIC_URL)
        ),
        name="redirect_pycortex_ctm",
    ),
    re_path(
        r"^media/images/(?P<collection_cid>\d+|[\w{}.-]{8})/(?P<pycortex_dir>[0-9a-zA-Z\^\&\'\@\{\}\[\]\,\$\=\!\-\#\(\)\.\%\+\~\_ ]+\_pycortex/)(?P<path>.*)$",
        serve_pycortex,
        name="serve_pycortex",
    ),
    re_path(
        r"^media/images/(?P<collection_cid>\d+|[\w{}.-]{8})/pycortex_all/(?P<path>.*)$",

neurovault/urls.py
import os
from django.conf import settings
from django.urls import include, path, re_path
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap, index

from neurovault.api.sitemap import (
    CollectionSitemap,
    ImageSitemap,
    CognitiveAtlasTaskSitemap,
)

admin.autodiscover()

sitemaps = {
    "Collections": CollectionSitemap,
    "Images": ImageSitemap,
    "CognitiveAtlasTasks": CognitiveAtlasTaskSitemap,
}

urlpatterns = [
    re_path("", include("social_django.urls", namespace="social")),
    re_path(r"^", include("neurovault.apps.main.urls")),
    re_path(r"^", include("neurovault.apps.statmaps.urls", namespace="statmaps")),
    re_path(r"^accounts/", include("neurovault.apps.users.urls", namespace="users")),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^api/", include("neurovault.api.urls", namespace="api")),
    re_path(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(r"^sitemap\.xml$", index, {"sitemaps": sitemaps}),
    re_path(r"^sitemap-(?P<section>.+)\.xml$", sitemap, {"sitemaps": sitemaps}),
]

statmaps/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from .models import Study, StatMap
from .views import edit_study

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Study.objects.all(),
            context_object_name='all_studies_list',
            template_name='statmaps/studies_index.html'),
        name='studies_list'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Study,
            template_name='statmaps/study_details.html'),
        name='study_details'),
    url(r'^statmap/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=StatMap,
            template_name='statmaps/statmap_details.html'),
        name='statmap_details'),
    url(r'^new$',
        edit_study,
        name='new_study'),
    url(r'^(?P<study_id>\d+)/edit$',
        edit_study,
        name='edit_study'),                   
    url(r'^(?P<study_id>\d+)/editstatmaps$', 
        "statmaps.views.edit_statmaps", 
        name="edit_statmaps"),
)

statmaps/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Study(models.Model):
    name = models.CharField(max_length=200, unique = True, null=False)
    DOI = models.CharField(max_length=200, unique=True, blank=True, null=True, default=None)
    description = models.CharField(max_length=200, blank=True)
    owner = models.ForeignKey(User)
    
    def get_absolute_url(self):
        return reverse('statmaps:study_details', args=[str(self.id)])
    
    def __unicode__(self):
        return self.name


def upload_to(instance, filename):
    return "statmaps/%s/%s"%(instance.study.name, filename)
    
class StatMap(models.Model):
    study = models.ForeignKey(Study)
    name = models.CharField(max_length=200, null=False, blank=False)
    description = models.CharField(max_length=200, blank=True)
    file = models.FileField(upload_to=upload_to, null=False, blank=False)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        unique_together = ("study", "name")

neurovault/apps/statmaps/templates/statmaps/_copy_md.html
<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelectorAll(".select-image").forEach(button => {
            button.addEventListener("click", function() {
                const dataValues = this.getAttribute("data-values");

                // Replace single quotes with double quotes
                let jsonString = dataValues.replace(/'/g, '"');
                // Replace True with true and False with false
                jsonString = jsonString.replace(/True/g, 'true').replace(/False/g, 'false');

                // Parse the JSON string
                const imageData = JSON.parse(jsonString);

                // Update text inputs
                document.querySelector("#id_name").value = imageData.name;
                document.querySelector("#id_description").value = imageData.description;
                document.querySelector("#id_modality").value = imageData.modality;
                document.querySelector("#id_map_type").value = imageData.map_type;
                document.querySelector("#id_target_template_image").value = imageData.target_template_image;
                document.querySelector("#id_cognitive_paradigm_cogatlas").value = imageData.cognitive_atlas_paradigm;
                document.querySelector("#id_cognitive_paradigm_cogatlas").title = imageData.cognitive_atlas_paradigm;
                document.querySelector("#id_cognitive_contrast_cogatlas").value = imageData.cognitive_contrast;
                document.querySelector("#id_number_of_subjects").value = imageData.number_of_subjects;
                document.querySelector("#id_contrast_definition").value = imageData.contrast_definition;
                document.querySelector("#id_cognitive_paradigm_name").value = imageData.cognitive_paradigm_name;
                document.querySelector("#id_cognitive_paradigm_short_description").value = imageData.cognitive_paradigm_short_description;
                document.querySelector("#id_cognitive_paradigm_description_url").value = imageData.cognitive_paradigm_description_url;
                document.querySelector("#id_figure").value = imageData.figure;
                document.querySelector("#id_age").value = imageData.age;
                document.querySelector("#id_statistic_parameters").value = imageData.statistic_parameters;
                document.querySelector("#id_smoothness_fwhm").value = imageData.smoothness_fwhm;
                document.querySelector("#id_race").value = imageData.race;

                // Update radio buttons and add active class to the corresponding label
                const updateRadioButton = (name, value) => {
                    const input = document.querySelector(`input[name="${name}"][value="${value}"]`);
                    if (input) {
                        input.checked = true;
                        document.querySelectorAll(`input[name="${name}"]`).forEach(radio => {
                            radio.closest('label').classList.remove('active');
                        });
                        input.closest('label').classList.add('active');
                    }
                };

                updateRadioButton("analysis_level", imageData.analysis_level);
                updateRadioButton("sex", imageData.sex);
                updateRadioButton("ethnicity", imageData.ethnicity);
                updateRadioButton("handedness", imageData.handedness);

                // Trigger change event for select elements to update select2
                $('#id_cognitive_paradigm_cogatlas').trigger('change');
                $('#id_cognitive_contrast_cogatlas').trigger('change');
                $('#id_target_template_image').trigger('change');
                $('#id_modality').trigger('change');

                $("#copyImageModal").modal("hide");

                toggle_cognitive_fields();
            });
        });
    });

    $(document).ready(function() {
        filterImages();
    });
</script>

neurovault/apps/statmaps/templates/statmaps/_papaya_viewer_content.html
<div id="NeuroVaultPapayaHolder" style: "width:1125px; height:1125px;"}
  .papaya{"data-params" => "params"}

neurovault/apps/statmaps/templates/statmaps/atlas_details.html
{% extends "base.html" %}
{% load static %}
{% block includes %}
{% endblock %}
{% block head %}
<script>
	(function() {
	  $(document).ready(function() {
	    $('#collection-tabs a:first').tab('show');
	    $('#image-details-datatable').dataTable({
	      sAjaxSource: "/api/images/" + "{{ api_cid }}" + "/datatable/?format=json",
	      iDisplayLength: 25
	    });
	    $('#image-regions-datatable').dataTable({
	      sAjaxSource: "/api/atlases/" + "{{ api_cid }}" + "/regions_table/?format=json",
	      iDisplayLength: 25
	    });
	    $('#delete_image').click(function(e) {
	      return confirm("Are you sure you want to delete this image? This operation cannot be undone!");
	    });
	    if (navigator.userAgent.indexOf("Safari") > -1 && navigator.userAgent.indexOf("Chrome") === -1) {
	      return $('a[href="pycortex"]').hide();
	    }
	    if($('#for_papaya').is(':visible')){
	         var params = [];
             params["worldSpace"] = true;
             params["expandable"] = true;
             params["smoothDisplay"] = false;
             params["showControls"] = false;
             params["allowScroll"] = false;
             params["images"] = ["{% static "images/"%}{{ image.target_template_image }}.nii.gz", "{{ image.file.url|urlencode }}"];
             params["luts"] = [{"name":"PuBu", "data":[[0,1,0.968627,0.984314],[0.125,0.92549,0.905882,0.94902],[0.25,0.815686,0.819608,0.901961],[0.375,0.65098,0.741176,0.858824],[0.5,0.454902,0.662745,0.811765],[0.625,0.211765,0.564706,0.752941],[0.75,0.0196078,0.439216,0.690196],[0.875,0.0156863,0.352941,0.552941],[1,0.00784314,0.219608,0.345098]]},
             {"name":"OrRd", "data":[[0,1,0.968627,0.92549],[0.125,0.996078,0.909804,0.784314],[0.25,0.992157,0.831373,0.619608],[0.375,0.992157,0.733333,0.517647],[0.5,0.988235,0.552941,0.34902],[0.625,0.937255,0.396078,0.282353],[0.75,0.843137,0.188235,0.121569],[0.875,0.701961,0,0],[1,0.498039,0,0]]}];

             var filename = "{{ image.file.url }}".replace(/^.*[\\\/]/, '')
             params[filename] = {"parametric": true,  "lut":"Spectrum", "alpha":"0.75",  minPercent: 0.0, maxPercent: 1.0};
             papaya.Container.startPapaya();
             papaya.Container.resetViewer(0, params);
        }

	  });
	}).call(this);
</script>
{% include "statmaps/_meta_image.html" %}
<meta name="pagetype" content="atlas">
<title>{% block title %}{{image.name}}{% endblock %}</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2>{{ image.name }}</h2>
        {% if not image.collection.private %}
        <p>Contributed by {{ user.username }} on {{ image.add_date|date:"N j, Y" }}</p>
        {% endif %}
        <p><b>Collection</b>: <a href="{{ image.collection.get_absolute_url }}">{{ image.collection.name }}</a></p>
        {% if image.description %}
            <p><b>Description</b>: {{ image.description }}</p>
        {% endif %}
        {% if image.tags.all %}
            <p><b>Tags</b>:
                {% for tag in image.tags.all %}
                    <a href="/images/tags/{{tag.name}}">tag.name</a>
                {% endfor %}
            </p>
        {% endif %}
        <a class="btn btn-primary btn-lg" href="pycortex">3D View</a>
        <a class="btn btn-primary btn-lg" href="{{ image.file.url|urlencode }}">Download</a>
        <a class="btn btn-primary btn-lg" href="http://neurosynth.org/decode/?neurovault={{ api_cid }}">Decode with neurosynth</a>
        {% if user_owns_image %}
            <a class="btn btn-primary btn-lg" href="{% url 'statmaps:edit_image' image.id %}">Edit details</a>
            <a class="btn btn-danger btn-lg" href="{% url 'statmaps:delete_image' image.id %}" id='delete_image'>Delete</a>
        {% endif %}

        <div class="row mt-1 mb-1">
        <div class="col d-none d-md-block" id="for_papaya" style="min-height:500px;">
            <div class="papaya"></div>
        </div>
        </div>
        <div class="row mt-1 mb-1">
            <div class="col">
                <h5>Metadata</h5>
                <div class="table-responsive-md">
                     <table id="image-details-datatable" class="table table-striped table-sm w-100">
                         <thead>
                            <tr>
                                <th>Field</th>
                                <th>Value</th>
                            </tr>
                         </thead>
                     </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h5>Regions</h5>
                <div class="table-responsive-md">
                     <table id="image-regions-datatable" class="table table-striped table-sm w-100">
                         <thead>
                            <tr>
                                <th>Intensity</th>
                                <th>Name</th>
                            </tr>
                         </thead>
                     </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
        <div class="card-header">Citation guidelines</div>
          <div class="card-body">
            <p class="card-text">If you use these data
                please include the following persistent identifier in the text of your manuscript:</p>
              <pre>https://identifiers.org/neurovault.image:{{ image.id }}</pre>
              <p class="card-text">This will help to track the use of this data in the literature.
                {% if image.collection.DOI %}
                    In addition, consider also citing <a href="http://doi.org/{{ image.collection.DOI }}">the paper related to this collection.</a>
                {% endif %}
            </p>
          </div>
        </div>
    </div>
</div>
<script type="application/javascript">
if($('#for_papaya').is(':visible')) {
    document.write('<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/rii-mango/Papaya@build-1449/release/current/minimal/papaya.js"><\/script>');
    document.write('<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/rii-mango/Papaya@build-1449/release/current/minimal/papaya.css"\/>');
}
</script>
{% endblock %}

neurovault/apps/statmaps/templates/statmaps/error_message.html
{% extends "base.html" %}
{% block head %}
<title>{% block title %}NeuroVault: a new home for all brain statistical maps!{% endblock %}</title>
<script type="text/javascript"> 
var addthis_config = {
     data_track_clickback: false 
} 
</script>
{% endblock %}
{% block content %}

<div style="width:90%; margin-left:42px; margin-top:30px">
<div class="alert alert-danger" role="alert" style="width:90%; margin-top:30px">
{{ error_message }}
</div>
{% endblock %}

neurovault/apps/statmaps/templates/statmaps/papaya_frame.html
{% extends "base.html" %}
{% load static %}
{% block global_includes %}

<style type="text/css">
body {margin:0;padding:0;background:none transparent;}
</style>
{% endblock %}
{% block head %}
{% include 'statmaps/_papaya_viewer_head.html' %}
<script src="{% static "scripts/jquery-1.10.2.min.js"%}" type="text/javascript"></script>
<script src="{% static "scripts/bootstrap.min.js"%}" type="text/javascript"></script>
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
<link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">

<script type="text/javascript">
     var params = [];
     params["worldSpace"] = true;
     params["expandable"] = true;
     params["images"] = ["{% static "images/MNI152.nii.gz"%}", "{{ image.file.url }}"];
     params["luts"] = [{"name":"PuBu", "data":[[0,1,0.968627,0.984314],[0.125,0.92549,0.905882,0.94902],[0.25,0.815686,0.819608,0.901961],[0.375,0.65098,0.741176,0.858824],[0.5,0.454902,0.662745,0.811765],[0.625,0.211765,0.564706,0.752941],[0.75,0.0196078,0.439216,0.690196],[0.875,0.0156863,0.352941,0.552941],[1,0.00784314,0.219608,0.345098]]},
     {"name":"OrRd", "data":[[0,1,0.968627,0.92549],[0.125,0.996078,0.909804,0.784314],[0.25,0.992157,0.831373,0.619608],[0.375,0.992157,0.733333,0.517647],[0.5,0.988235,0.552941,0.34902],[0.625,0.937255,0.396078,0.282353],[0.75,0.843137,0.188235,0.121569],[0.875,0.701961,0,0],[1,0.498039,0,0]]}];

     var filename = "{{ image.file.url }}".replace(/^.*[\\\/]/, '')
     params[filename] = {"parametric": true,  "lut":"OrRd", "negative_lut":"PuBu", "alpha":"0.75"};

     $(document).ready(function() {
        $('#NeuroVaultPapayaHolder').addClass('well');
        $('#NeuroVaultPapayaHolder').prepend($('<div style="margin: 8px;"><h4>NeuroVault Image: <a target="_top" href="http://{{ request.get_host }}{% url 'statmaps:image_details' image.pk %}">{{image.name|truncatechars:35}}</a></h4></div>'));
        $('#NeuroVaultPapayaHolder').css("width","470px").css("height","auto").css("padding","5px");
        $('#NeuroVaultPapayaHolder').append($('<div style="height: 90px; overflow: auto; margin: 7px;"><p><b>Description:</b> {{image.description}}</p></div>'));
    });

</script>

{% endblock %}


{% block body %}
<body style="background-color:transparent">
<div id="#NeuroVaultPapayaHolder" style="width:470px; height: auto;"
     class="papaya" data-params="params"></div>
</body>
{% endblock %}